### ISSUE TITLE
System cannot find Antumbra Device

### ISSUE THREAD

**Issue by btgarner** [TeamAntumbra/wintumbra#1]
Followed directions on https://github.com/TeamAntumbra/wintumbra/blob/master/README.md ; Antumbra device was listed under USB (not Other), did as directed.  Started antumbra.exe process, clicking any option in the status bar gets a "No Devices were found" error.

running Win7 Home Premium SP1
Processor: Inel i7 CPU Q740 @ 1.73 GHz
Ram: 8 GB
64 bit OS

Will try on win 8.1 system

**Comment by walshie4** [comment]
Have you tried the most recent release? There is a driver installer inside the output directory under `driver/`.

**Comment by btgarner** [comment]
this is from the drivers that I get directed to going to antumbra.io/beta

on win 8.1, the drivers will not install either.  Get a dialog box that says:

Windows found driver software for your device, but encountered an error while attempting to install it.
Glow
The third-party INF does not contain digital signature information
If you know the manufacturer of your device, you can visit its website and check thesupport section for driver software.

**Comment by walshie4** [comment]
Try [this](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.1.3-beta) version. You'll need to copy the two .dll files into the output directory from the setup.exe, then a driver installer will be inside a `driver/` directory.

**Comment by btgarner** [comment]
Despite the error, the antumbra software does seem to see the device on the 8.1 machine.  However it does not seem to do anything.  I am just getting a soft faint green glow from the device.  Output speeds for dev0 are 8.553 hz; there is also a dev1 device with 0 hz output speed.  Any changes do not seem to affect the hardware.

**Comment by walshie4** [comment]
Have you tried quitting the software, unplugging and re-plugging and then re-starting the software?

**Comment by btgarner** [comment]
Pretty much the same response.

After loading that other installer and dev driver.  Launching the antumbra exe, still no device according to all parts of the app.  And the antumbra is just glowing with a faint green glow.

**Comment by walshie4** [comment]
Try turning off windows signed drivers only policy (at the moment ours is not signed, will be soon) as shown [here](http://www.craftedge.com/tutorials/driver_install_windows8/driver_install_win8.html). Then re-run the driverInstaller and see if that fixes it.

**Comment by walshie4** [comment]
It also may help your case to use [this tool](http://zadig.akeo.ie/) to install the WinUSB driver for the Glow Device. Just plug in your Glow, open up the tool, select options -> List all devices, and then find your Glow in the top drop down box. Select WinUSB below, and click the big install button.

**Comment by btgarner** [comment]
the Zadig tool made no difference on the W7 machine.  And re-installing on the W8.1 machine with the unsigned drivers also made no difference on that machine.  I have one other Win8.1 machien I can try this on.

**Comment by walshie4** [comment]
Try downloading the `.inf` file that's hosted with the download Then right click on it and select install.

**Comment by btgarner** [comment]
![ant_error](https://cloud.githubusercontent.com/assets/9194420/6312194/fbac6618-b93e-11e4-8768-f27d53e39b40.png)

**Comment by walshie4** [comment]
I was referring to [this `.inf` file](https://github.com/TeamAntumbra/wintumbra/releases/download/V0.1.3-beta/antumbraglowv3beta.inf) which should support installing through the right click menu. Is that the one you tried to install above?

**Comment by btgarner** [comment]
It was not, but now I have, and it is not behaving any differently.
![ant_err2](https://cloud.githubusercontent.com/assets/9194420/6312552/09a3476c-b94b-11e4-8a98-1d072267dd62.png)

**Comment by walshie4** [comment]
Try downloading the new driver installer [here](https://www.dropbox.com/s/brerdk5mqstf5eu/glowdrvinst.zip?dl=0).  Just double click glowdrvinst.exe and it will install WinUSB for Glow if it's not already associated with a driver (so go to Device Manager and Uninstall + check "Delete driver software")
if it is already associated with a driver, i.e. it has already been installed, it will do nothing.  Then re-start the app to test.

**Comment by walshie4** [comment]
Just posted a new release. Try following the new install instructions (including uninstalling the old driver) and let me know how that goes.

**Comment by btgarner** [comment]
Same result "No devices were found" on the Win7 machine

**Comment by walshie4** [comment]
And just to be clear you're also unplugging and plugging back in your device, as well as restarting the app?

**Comment by btgarner** [comment]
Yes, I have even rebooted a few times, all to no avail.  =(

**Comment by walshie4** [comment]
Try deleting all Antumbra software including the driver through device manager and then reinstall the latest release.

**Comment by btgarner** [comment]
Deleted everything, uninstalled drivers from the DevMgr, uninstalled all programs available in the control panel.  Downloaded the new setup, ran it.  Plugged in device, got this:

![ant_err3](https://cloud.githubusercontent.com/assets/9194420/6315759/85d21b8a-b9da-11e4-9df8-a5e342fdd2ff.png)

Went into the DriverInstall directory, and ran glowdrvinst manually.  Unplugged device, then plugged it back in.  Still get the "No Devices Installed" message from the application.

**Comment by walshie4** [comment]
When you go into device manager what does Glow show up under, and as?

**Comment by btgarner** [comment]
Okay, I was able to get the new setup run on the other win8 machine, and it installed just fine, and then ran the application.  It behaves just like the other Win8 machine, I just get a soft green glow from the device.  Is this what I should be seeing?

![2015-02-21 15 14 51](https://cloud.githubusercontent.com/assets/9194420/6315990/d079708c-b9e1-11e4-820d-12447280ba5e.jpg)

**Comment by walshie4** [comment]
The green glow means that the device has started up successfully. Without unplugging the Glow click on the little A, select quit. And then re-run `Antumbra.exe`. Once running once again select start, and see if the color changes.

**Comment by btgarner** [comment]
Okay. I plugged the Device into a power USB hub (rather than directly), and it worked, but plugging it back into the laptop (directly) does not work.  I have repeated this process several times, and it is fairly consistent.  Plugged into a powered hub works fine, plugged directly into the laptop and it does not work.

**Comment by DavisFoster** [comment]
Hey - sounds like this could be a strange edge-case hardware issue.  

Just clarifying a few things:
-A soft green glow means the firmware boot was successful, and the Glow should be ready to talk to a computer.  If you AREN'T getting a green glow when plugged into certain computers, this likely means that either:  A.  USB power regulation on that computer is bad, causing the device to fail, B.  the computer doesn't want to output the 500mA required by Antumbra (USB2.0 Noncompliance).

If the device is green when initially plugged into both the powered hub and the PC, but is only capable of changing colors / etc when attached to the hub, there might be a different issue altogether.  Please advise.

**Comment by btgarner** [comment]
I saw the latter, where the soft green glow was visible from both the laptop and the hub, but the application only recognized the device via the powered hub, and thus I could only see changes in colors via the powered hub.

I am willing to do whatever you need to help figure this out (for science!), and since we seem to have a clearer path as to the problem, that's a step in the right direction.

**Comment by DavisFoster** [comment]
Try unplugging the hub and plugging Glow back into the same USB port that hub was plugged into.  Restart the app and try again.  This will rule out the other USB ports as being dead.   

If that doesn't work, try a couple different microUSB cables if you have them - the 6ft one might be too long to be driven from your computer (either due to voltage drop or weak data drivers).  

If it still doesn't work after both of those, it might be a firmware issue of some kind.  If you have access to a Mac, I highly suggest trying that out (with the included cable) so we can (mostly) rule out a strange hardware issue.  

Are you having this same result on your other PCs?

**Comment by btgarner** [comment]
My laptop has a lot of USB ports.  I tried the Antumbra directly into 4 separate USB ports (including the one the hub was plugged into), and could not get any response from the device, other than the green glow.  I tried a separate cable, and that would not work, even on the powered hub.

And yes, this is what I was seeing on the Win8 machines (2 of them), I would see a device listed, but the until would do nothing other than have the green glow.  I have not tried using a powered USB hub on those other machines.  I can, but it will take some time to re-wire a few things.

**Comment by DavisFoster** [comment]
Great news - I was able to replicate the bug on a Win8 system, and think I know how to fix it.  
1.  Quit all glow software.  
2.  Uninstall all current glow software.  
3.  Download the latest build. 
4.  PLUG IN GLOW, then install using the setup installer. 
   --Test it here - if it works, great.  If not --- 
5.  In the top level directory (should be "Antumbra"), find the folder DriverInstaller and run glowdrvinst.
6.  Ensure that glowdrvinst runs to completion - you should get a command prompt window, and it'll say something along the lines of "Install successful, press enter to quit" once it's done. 
7.  Run the Antumbra software.  

Finally, configure it how you want, ensure it sees device 0, then click start.  Should work!  Let me know.

EDIT:  If you re-install with Glow plugged in, the driver should automatically install.

**Comment by btgarner** [comment]
Um, well, that did not work.  I uninstalled the software and drivers.  Then used the new setup, installed the driver(s).  Launched the application.  All I am getting now is a soft blue glow from the device.

**Comment by DavisFoster** [comment]
Did you install everything with the device plugged in?  It will not work otherwise.    

Soft blue glow means that the device is in bootloader mode and ready to accept new code - this is because is saw a signal on the MOSI pin - (this is an odd error).  Try unplugging the device, plugging it in again (should be green), and then running Antumbra and hitting Start.  

If that doesn't work, uninstall everything, delete all the files, go to device manager and uninstall antumbra drivers, and then reinstall from the latest build with Antumbra plugged in.  

If that STILL doesn't work, I highly urge you to track down a Mac (maybe a friend, work, library, etc) has one that you can access - and then run the Mac build.  Because OSX is a Unix system (meaning it handles external devices in a sane way), it will almost certainly let us rule this out as a hardware issue.

**Comment by DavisFoster** [comment]
@btgarner  - Any luck?  It seems like you're the only one currently this bug, so we're trying to figure out what edge-case might be causing it (and get it cleaned up).

**Comment by btgarner** [comment]
I removed everything from the Win 8 machine, then grabbed the latest setup.  Installed it and launched the new application (notice that teh driver was not needed as a separate install, nice).  However the result was the same, just the dull green glow.  So I tried the trick that made the device work on my Win7 machine, plugging it into a powered USB hub, and it fired right up, as expected.

So, for whatever reason, the device I have seems to only work when plugged into a powered USB hub.  This is the observed behavior on 2 separate machines (one Win7, one Win8.1), by 2 different manufacturers (Dell, Asus).

**Comment by DavisFoster** [comment]
Huh - that's a VERY strange failure, especially with two different PCs from two different manufacturers.  We've had no issues (aside from software bugs) getting any of our devices to talk to any of our machines (multiple different PCs and Macs, laptops and desktops, etc).  Doesn't seem like any other users are experiencing this problem either.  

I don't mean to sound like a broken record, but try the device on a Mac and see if it still doesn't work (without a hub).  Although power / data issues seem unlikely on two separate machines, it's plausible.  

If you want, we'd be happy to take the device back (and ship you a replacement).  If the device exhibits the same failure mode on a Mac, I'm very interested in doing a postmortem / debug on it.

**Comment by btgarner** [comment]
I have a 7+ year old MBP, that I might be able to resurrect and test on.  Its not a great machine, and shows its age, so I am not sure how valid of a test that will be.  I also hava a Hackintosh (Dell Mini) that I can try it on, but again, have no idea how great of a test that is.

**Comment by DavisFoster** [comment]
Don't bother with the old MBP, we require 10.7+ for our software, which you almost certainly aren't running.  If the hackintosh is (mostly) up to date, I'd give it a shot there - our Mac dev did plenty of work on Antumbra with his hackintosh.

**Comment by btgarner** [comment]
The Dell Mini Hackintosh is not running anything current (10.5, maybe 10.6).  I do have a Win 8 tablet that I can try this on, but have no other Mac hardware.

**Comment by DavisFoster** [comment]
Give it a shot on the Win8 tablet.  If you are confident that your test procedure (the order you plug things in, start software, start glow, etc) is the same with / without the USB hub, and it fails on every device without the USB hub, we'd be glad to take the device back and get you a new one.

**Comment by DavisFoster** [comment]
@btgarner  - Any updates?  We'd love to take a look at your unit if it still isn't working.  This (could be) a bug that can't make it into the production rev.  Thanks!

**Comment by btgarner** [comment]
nothing yet.  was without power for over a day due to that storm, tomorrow I will give it a try

**Comment by btgarner** [comment]
I have tried everything I can think of with the Win8 tablet, and cannot get it to work.  I tried directly (green glow).  Tried a USB hub that powered and had nothing else in it (green glow).  Then I tried the hub that has been working with the other machines, nothing, still just the green glow.

**Comment by DavisFoster** [comment]
Shoot me an email at davis@antumbra.io - we'll take the unit back to try and diagnose any problems, and then ship a new working unit back to you.  Still not sure what is actually causing the problem here - hopefully we can get it diagnosed and fixed ASAP.
