### ISSUE TITLE
Direct3D capture should not crash when mandatory settings are not entered

### ISSUE THREAD

**Issue by CreamyG31337** [TeamAntumbra/wintumbra#10]
If you enable Direct3D capture and press start the application will become unresponsive. Clicking settings and entering an exe to monitor resolves this.

**Comment by alystair** [comment]
Ironically it also crashes for me if I attempt putting in a proper executable.

**Comment by CreamyG31337** [comment]
That's weird. I am not surprised, though. Mine doesn't crash once I put the exe, but it doesn't actually capture anything either. There's so many bugs I'm not sure why they gave us a tracker. Surely they don't need help finding bugs. Just click anything, it will probably crash. :(

**Comment by CreamyG31337** [comment]
One other thing related to this, entering anything into the 'process to capture' field also results in the same behavior if the exe is not valid and running already when you press start, so: 
1) put an OK button and validate the file exists when clicking that
and consider for the future:
2) put a browse button and allow user to select a file
3) put another button to select a running process
4) save the setting so I don't have to do this every time

**Comment by walshie4** [comment]
Direct3D capture plugin now will automatically find the foreground process, as of 27abde017d4829a98e1b0b7da177efbc09c05835. Expect this extension to be receiving a _lot_ of attention once core stability and usability issues are cured.
