### ISSUE TITLE
base color tweaker needed

### ISSUE THREAD

**Issue by alystair** [TeamAntumbra/wintumbra#14]
One of the primary problems I find with the Antumbra at the moment is that the base color is not "pure white", if we could get a primitive tool to adjust the base values to a "pure" white pre-process I think the end results would look a lot nicer.

**Comment by DavisFoster** [comment]
Strategy add: 

Blue-yellow bias slider, and green-magenta bias slider.  These values should be multipliers that automatically shift all values before they hit the output (decorator).  White balance is only really necessary in the range where R,G,B are all within 30/255 from each other, so if it's problematic, cases where this isn't true can be automatically passed through without tweaks.

**Comment by walshie4** [comment]
Starting in [V0.2.1-beta](https://github.com/TeamAntumbra/wintumbra/releases/tag/v0.2.1-beta) there is now a white balancer which will bias output colors per your settings. Please see the release notes for an overview of how it works.
