### ISSUE TITLE
Why not use the wheel interface for white calibration?

### ISSUE THREAD

**Issue by alystair** [TeamAntumbra/wintumbra#17]
It took me a whole of 3 seconds to find the "true white" spot dragging the center point around on the color wheel, while it's been more than 3 minutes of me "hand tweaking" to try and get the same values.

From a UX perspective during initial setup of a device, using the wheel method would be ideal.

**Comment by walshie4** [comment]
Good idea!

**Comment by walshie4** [comment]
See release [V0.2.2-beta](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.2.2-beta) which implements this change.
