### ISSUE TITLE
Windows 10 Driver Issue

### ISSUE THREAD

**Issue by supergregg** [TeamAntumbra/wintumbra#22]
Hi.
Im running the latest Windows 10 Build 10130, i know, i know its Beta and all but they will be releasing it quite soon and it would be nice to have it working for all who upgrade day 1.
Here are the issues I'm having:
Setup and Driver installs without problem, Glow is detected in device manager but the software does not recognize the Glow. I have solved the issue by forcing it to install the drivers from the install folder. However after a reboot i have to do it all over again.

The Whitebalance feature does not always work. However, this might not be a Win10 specific issue.
What happens is that it worked to set Whitebalance the first time but the second time opening it does nothing and i have to do a "off and on" to see the temperature change. So it does set whitebalance but not so that i can see it in real time.
I'm goint to try Game Mode now. -> Feature request here, maybe some way to detect if a game is running and autosetting to GameMode?

**Comment by walshie4** [comment]
Our embedded dev @pharada and I will be investigating the Windows 10 driver issue as that is certainly Windows 10 specific.

As for the white-balance I can't seem to reproduce the issue per your instructions (on Windows 7).  Are you referring to the second time opening the white-balance window or the app?

Finally the game mode capture can grab the desktop screen as well (although it is usually less performance friendly), we may add the auto-detection for 'game mode' however this is not a very easy fix.  Our only friend in this area is a `dll` call which can get us the running foreground process name, however without a list of all games this information is nearly useless.  This is definitely something we have in mind though.

**Comment by supergregg** [comment]
I'm not sure about the whitebalance. As Its a hassle to get things going, this might get solved if the driver issue gets solved. At least then I can test it more thoroughly.

**Comment by eedwardsdisco** [comment]
@walshie4 Regarding process detection, what about saving a list of processes, or popping up a menu that lists processes and letting us choose one? ShiftWindow, NVidia Game Profiles, and RivaTuner are examples.

**Comment by walshie4** [comment]
@eedwardsdisco  This was the old process when game capture needed to inject into the game process, however it is no longer the choosing of the process that matters but rather the switch to game mode if you want to be able to capture any DirectX rendered content.    You can actually run game mode all the time and it will work, however it will probably have worse performance.

**Comment by walshie4** [comment]
Can you check if the build mentioned [here](https://www.reddit.com/r/antumbraglow/comments/3jrw76/v100_prerelease_testing/) still has the same problem?

**Comment by walshie4** [comment]
Closing as stale, let me know if this issue persists.
