### ISSUE TITLE
Multi-Glow Support Broken

### ISSUE THREAD

**Issue by eedwardsdisco** [TeamAntumbra/wintumbra#24]
0.2.9.0

With the removal of the advanced features button, I can no longer use both glows.

I have 2 glows attached to my second monitor. I used to be able to assign 1 glow to each half of the monitor.

The Mirror\Augment settings only activate the primary glow, and the 'set capture area' is only for the primary, as well.

Game mode activates both glows, but only works on the primary monitor, ignoring the capture setting entirely.

Preferentially I want to be able to assign 1 glow to each half of my secondary monitor (like previous behavior).

**Comment by walshie4** [comment]
You still can.  When you click `Set Capture Area` it will open the first device's capture window and change to `Next Device`.  Clicking that will open the next devices mirror window.  When you close these the devices will resume their previous mode, or you can click one of the mirror mode buttons (other than game).  There is an issue when starting mirror mode which sometimes causes only one device to start however, simply re-clicking your desired mode usually fixes this.  Game mode is only single monitor right now, however we are currently working on this.

**Comment by eedwardsdisco** [comment]
Oh wow, thank you! I definitely had not noticed that.

Looking forward to the Game Mode change. I'll go ahead and close this issue.
