### ISSUE TITLE
Turn Off on Standby Issue

### ISSUE THREAD

**Issue by jarnoburger** [TeamAntumbra/wintumbra#25]
The software does not turn off the glow when i place my pc in standby..
Making my room glow when i want to go to sleep..

**Comment by walshie4** [comment]
This feature has been implemented for quite some time.  What version of Windows are you running?  Working on Windows 7 with hibernate, lock and sleep.

**Comment by walshie4** [comment]
Closing as stale, let me know if this issue persists.
