### ISSUE TITLE
Multiple Glows, separate capture areas?

### ISSUE THREAD

**Issue by scottt732** [TeamAntumbra/wintumbra#26]
0.2.7 had an Advanced feature which let me configure each glow independently (specifically the capture area).  The feature seems to be gone in recent builds.

I have 3x Glows behind 3 monitors.  I would like each device to respond to the contents of their own screen.  Recent versions synchronize all devices to what's on the center screen (in Augment mode).

Is the Advanced menu coming back?  If not, it would be really nice to have the ability to map each device to a monitor and have the coordinates figured out automatically (i.e., not having to set the capture areas manually).

**Comment by eedwardsdisco** [comment]
Hah! I had literally the same complaint yesterday after the update. See this issue along with solution from developer: https://github.com/TeamAntumbra/wintumbra/issues/24

Turns out we're bad at noticing the button change :)

**Comment by walshie4** [comment]
:P I'll make this more apparent in a future release as it is very subtle for a much needed feature.

@scott732 The advanced menu _will_ be coming back soon.
