### ISSUE TITLE
Problem through an HDMI media amp? (Onkyo TX-NR626 in this case)

### ISSUE THREAD

**Issue by khei** [TeamAntumbra/wintumbra#27]
Installed and sets up ok, has green light but not getting any response. 

Main screen (ie. setup to run Win startmenu on) is a Sony 55 Smart LED-TV KD-55X8505BAE. Have different res in the dual screens; tv 1920x1080/pc:1376x768.

Using an Onkyo TX-NR626 connected from pc to "HDMI-PC in" and "HDMI-Main Out" to tv .  

Can I expect it to work?

**Comment by walshie4** [comment]
As long as the computer which is serving the image has Glow plugged into it, yes.

**Comment by walshie4** [comment]
Any news here?

**Comment by khei** [comment]
Got it working (by turning on /setting)

& sry for late reply, been away.

2015-09-05 20:27 GMT+02:00 Adam Walsh notifications@github.com:

**Comment by walshie4** [comment]
No problem, good to hear.
