### ISSUE TITLE
Adjusting white balance causes black to no longer display as black 

### ISSUE THREAD

**Issue by glowglowflow** [TeamAntumbra/wintumbra#28]

**Comment by walshie4** [comment]
What are you seeing black show up as?

**Comment by glowglowflow** [comment]
Example: Adjust white balance so there is more red in the mix. When screen is black glow is a deep red color.

**Comment by walshie4** [comment]
Resolved 0bb86c4e0878a201d14b8e4e51e6f4047a317d8f
