### ISSUE TITLE
Antumbra notification window

### ISSUE THREAD

**Issue by ghost** [TeamAntumbra/wintumbra#3]
Antumbra notifcation window doesn't play nice with the Windows 8.1 notification window.  When Antumbra window is in front of 8.1, and I click in the area of overlap, the 8.1 windows comes in front, as shown.

![image](https://cloud.githubusercontent.com/assets/11161061/6341064/6647bcaa-bb94-11e4-933b-270dcce05bb9.png)

**Comment by walshie4** [comment]
Try [V0.1.16-beta](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.1.16-beta), should fix it.

**Comment by ghost** [comment]
Looks good!

**Comment by walshie4** [comment]
Still happens on occasion. :/

**Comment by DavisFoster** [comment]
@walshie4 - This was happening with v0.1.15 on Windows 8 for me yesterday.

**Comment by walshie4** [comment]
@DavisFoster  try v0.1.16 (or later) it has the partial fix.

**Comment by walshie4** [comment]
Seems to be fixed, can no longer reproduce.

**Comment by DavisFoster** [comment]
Issue still present in 0.1.19 on Windows 7.

**Comment by walshie4** [comment]
No longer relevant as mentioned in above commit, will close after pushing release with fix (probably later on today).
