### ISSUE TITLE
Multiple monitor issues

### ISSUE THREAD

**Issue by batfasturd** [TeamAntumbra/wintumbra#30]
Will the issue with multiple monitors ever be solved? I still have a non functional glow since launch because I have multiple monitors. I bought this for playing games late at night and it has yet to function for this purpose.

**Comment by walshie4** [comment]
Please let me know if this does not fix it.

**Comment by batfasturd** [comment]
After spending an hour plus trying to get it to compile it did work. I tip my hat and extend many thanks to you good sir. My glow is now working with games and as intended. I shall post and sing of your name on the reddits and possibly upload the binary since I know I am not the only one with this issue.

**Comment by walshie4** [comment]
Should have linked to it previously, a binary is available https://github.com/TeamAntumbra/wintumbra/releases/tag/v1.0.0_RC3. Great to hear it's working! :)

**Comment by batfasturd** [comment]
lol, well crap, that would have saved me some time but I am grateful nonetheless. Thanks again.
