### ISSUE TITLE
Antumbra client not staying open

### ISSUE THREAD

**Issue by ghost** [TeamAntumbra/wintumbra#31]
I have the 2.9.1 client. It worked great until recently, when it started to close out soon after opening. I run the executable, the icon appears in the tray, and before it even starts mirroring or can bring up the client window, it closes itself. This persists between reinstallations. I can confirm that I get the green ready glow from the device.

**Comment by walshie4** [comment]
Try out https://github.com/TeamAntumbra/wintumbra/releases/tag/v1.0.0_RC3

**Comment by ghost** [comment]
The software no longer quits on its own, but it's also not controlling the
glow. All I get is a steady green ready light.

**Comment by ghost** [comment]
Still having problems with the software not controlling the glow. Also
appears to be missing game-compatible mode.

**Comment by walshie4** [comment]
I'll be re-setting up my bootcamp situation and be taking a look this evening 👍  

Sorry for the delay.

**Comment by ghost** [comment]
If it helps, I was uninstalling a bunch of old C++ redistributables a
couple days before I saw the original problem. Are there any log files I
could grab for you?

**Comment by walshie4** [comment]
Yeah there should be one inside your AppData directory.  It will be nested like so `AppData/Antumbra/wintumbra.log`

**Comment by ghost** [comment]
Here you go.

**Comment by walshie4** [comment]
I imagine you attached that to the email, can you upload it here instead? I don't have email notifications turned on.

**Comment by ghost** [comment]
[wintumbra.txt](https://github.com/TeamAntumbra/wintumbra/files/799668/wintumbra.txt)

**Comment by walshie4** [comment]
Try out the new release (https://github.com/TeamAntumbra/wintumbra/releases/tag/v1.0.0) and let me know if the issue persists

**Comment by ghost** [comment]
There appears to be no change. Here's the log file.
[wintumbra.txt](https://github.com/TeamAntumbra/wintumbra/files/825500/wintumbra.txt)

**Comment by ghost** [comment]
I recently upgraded to windows 10, and this seems to have fixed whatever
issue was preventing operation. Thanks again for making such an awesome
product!

**Comment by walshie4** [comment]
Glad you got it resolved! Sorry I couldn't have helped more.  I'm hoping to do some polishing of the loading / initialization process in the near future.
