### ISSUE TITLE
Exception While Starting

### ISSUE THREAD

**Issue by glowglowflow** [TeamAntumbra/wintumbra#32]
Clean install of windows 10 and after installing wintumbra I'm getting an "Exception loading extensions, Key not found: extension.glow.extensionframework.glowextension"

Hmm, worked before I did a clean install of windows.

**Comment by walshie4** [comment]
please include the log file found in `AppData/Antumbra/wintumbra.log`

**Comment by glowglowflow** [comment]
Good to hear from you, hope all is well. 
[wintumbra.log](https://github.com/TeamAntumbra/wintumbra/files/1608221/wintumbra.log)

**Comment by walshie4** [comment]
Good to see people are still using Glow :)

From your log it looks like you don't have the SlimDX supporting package installed.  It should be installed when you run the Glow installer though.  

It looks like I may need to update the installer, may have gotten lost in an update shuffle.  For now you can get what you need by installing the `End User Runtime` for SlimDX from here https://slimdx.org/download.php

Let me know if you still run into issues after installing that.

**Comment by glowglowflow** [comment]
Well I just came back to it today, and it launched without me installing anything different. Everything seems to be working correctly now. Windows did do an update during one of the shutdowns in the past couple days, perhaps it sorted itself out. Here's a new log
[wintumbra.log](https://github.com/TeamAntumbra/wintumbra/files/1610201/wintumbra.log)

**Comment by walshie4** [comment]
🤷‍♂️  good to hear!
