### ISSUE TITLE
Save chosen extensions and settings, add reset to default button

### ISSUE THREAD

**Issue by CreamyG31337** [TeamAntumbra/wintumbra#8]
Application should remember enabled plugins and plugin settings. Once this is done please add a way to reset back to the defaults in case of a problem.

**Comment by walshie4** [comment]
Partially fixed in [V0.1.19](https://github.com/TeamAntumbra/wintumbra/releases/tag/V0.1.19-beta) extensions that have custom settings retain them after clicking save. Will close after implementing remembering enabled plugins, core settings, and reset feature.

**Comment by walshie4** [comment]
A simple version of this feature is now available in V0.2.0.  Being able to name saved configs under a custom name and list saved setting configs will be implemented soon.
